# Generated by Django 4.1.3 on 2022-11-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
