# Generated by Django 4.1.3 on 2022-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
