# Generated by Django 4.1.3 on 2022-11-26 11:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0005_alter_contact_recovery_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='ZA'),
        ),
        migrations.AddField(
            model_name='contact',
            name='recovery_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='ZA'),
        ),
    ]
