# Generated by Django 4.1.3 on 2022-11-17 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hlulihlawu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default="It's a cake", max_length=250)),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='default-cake.jpg', upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_key', models.CharField(choices=[('1126', 'Cakes'), ('1267', 'Cupcakes'), ('2672', 'Cookies')], default='1126', max_length=100)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('P', 'Party')], default='M', max_length=100)),
                ('flavour', models.CharField(choices=[('V', 'Vanilla'), ('C', 'Chocolate')], default='V', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hlulihlawu.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('transaction_id', models.CharField(default=hlulihlawu.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('orderitems', models.ManyToManyField(to='hlulihlawu.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
