# Generated by Django 4.1.3 on 2022-11-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orders_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_for_orders', to='hlulihlawu.order'),
        ),
    ]
