# Generated by Django 4.1.3 on 2022-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0003_remove_orderitem_orders_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(default='order_id not presented', editable=False, max_length=36),
        ),
    ]
