# Generated by Django 4.1.3 on 2022-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0005_alter_product_product_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavour_avail',
            field=models.BooleanField(default=True),
        ),
    ]
