# Generated by Django 4.1.3 on 2022-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0007_order_completed_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.CharField(choices=[('ordered', 'Order Placed'), ('preparing', 'Being Prepared'), ('prepared', 'Completed, awaiting delivery'), ('complete', 'Delivered, Complete')], default='ordered', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002485A1DC0A0> order', max_length=50),
        ),
    ]
