# Generated by Django 4.1.3 on 2022-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0009_alter_order_name_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000016E0ECF40D0> order', max_length=50),
        ),
    ]
