# Generated by Django 4.1.3 on 2022-11-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0011_rename_product_orderitem_products_alter_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001C56E8240D0> order', max_length=50),
        ),
    ]
