# Generated by Django 4.1.3 on 2022-11-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0012_alter_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='open',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='products',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hlulihlawu.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002356B0D00D0> order', max_length=50),
        ),
    ]
