# Generated by Django 4.1.3 on 2022-12-19 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0021_rename_address_shippingmodel_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmodel',
            name='building',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 22, 9, 54, 673531, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000208783F0280> order', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingmodel',
            name='zipcode',
            field=models.CharField(max_length=4),
        ),
    ]
