# Generated by Django 4.1.3 on 2022-12-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0027_alter_order_created_alter_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmodel',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hlulihlawu.shippingmodel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000027657AB0280> order', max_length=100),
        ),
    ]
