# Generated by Django 4.1.3 on 2022-12-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0028_remove_shippingmodel_order_order_shipping_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000193ABFCC130> order', max_length=100),
        ),
    ]
