# Generated by Django 4.1.3 on 2022-12-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0029_remove_cartitem_order_id_alter_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002BC9629C130> order', max_length=100),
        ),
    ]
