# Generated by Django 4.1.3 on 2022-12-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0030_alter_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_model',
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(choices=[('gauteng', 'Gauteng'), ('eastern-cape', 'Eastern Cape'), ('free-state', 'Free State'), ('kwaZulu-natal', 'KwaZulu-Natal'), ('limpopo', 'Limpopo'), ('mpumalanga', 'Mpumalanga'), ('northern-cape', 'Northern Cape'), ('north-west', 'North West'), ('western-cape', 'Western Cape')], default='gauteng', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001C05F0202B0> order', max_length=100),
        ),
        migrations.DeleteModel(
            name='ShippingModel',
        ),
    ]
