# Generated by Django 4.1.3 on 2022-12-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0037_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000027386E04130>--None', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000027386E04130> order', max_length=100),
        ),
    ]
