# Generated by Django 4.1.3 on 2022-12-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlulihlawu', '0039_alter_order_name_alter_order_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001EF23C24A90> order', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001EF23C24A90>--None', max_length=200),
        ),
    ]
